### ISSUE TITLE
Fanart.tv

### ISSUE THREAD

**Issue by MichaelTiebesl** [metabrainz/picard-plugins#53]
I can't get the plugin installed. I have downloaded the plugin fanart.tv cover art from the website [https://picard.musicbrainz.org/plugins/](url).
Extract it and put the folder fanarttv in the plugin folder from Picard. 
I followed the instructions from this website [https://forum.fanart.tv/viewtopic.php?f=5&t=262](url)
but i can't enable the plugin.

After restart Picard i get this:

![1](https://cloud.githubusercontent.com/assets/10792019/15168362/79cbf364-1763-11e6-8c8a-23f5ecec002a.png)

I can't see unfortunaly the plugin in the list from Plugins in Picard.

![2](https://cloud.githubusercontent.com/assets/10792019/15168387/ba14038a-1763-11e6-97d1-9c438455ae4c.png)

So what do i wrong here?
I use Ubuntu 16.04 and Picard version 1.3.2

Thanks

**Comment by phw** [comment]
Unfortunately due to a fix the plugin currently only works with the development version of Picard. You can download daily builds from the Picard download page. Or you install an older version of the plugin by downloading it from Github. I think https://github.com/metabrainz/picard-plugins/blob/0a0c52c88d0a48438f6aef98fc235e1199722ded/plugins/fanarttv/__init__.py is the last version working with 1.3.

We need some way to avoid such plugin breakage in the future :( The easiest is probably to have a development branch for the upcoming release. All changes incompatible with the release version have to go there.

**Comment by MichaelTiebesl** [comment]
@phw Thanks for your time. I downgrade the plugin from Github with the link you provided. Everything is working fine now.
